version: "3.1"

services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"

  ipfs:
    image: ipfs/go-ipfs
    volumes:
      - ./tmp/ipfs_staging:/export
      - ./tmp/ipfs_data:/data/ipfs
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"

